### ISSUE TITLE
Binaries folder has .config files, missing latest binaries, assemblies

### ISSUE THREAD

**Issue by ultramoto** [Wagnerp/Krypton-NET-4.72#2]
The binaries folder has .config files in it, but no pre-built binaries. Might be good to include that as many folks will just want to reference the latest assemblies, instead of building the entire framework. 

Also, noticed that the installer is using an unknown script technology (not WIX). Not sure how to build that project.

**Comment by Wagnerp** [comment]
Hi @ultramoto,

Thanks for your comment. We don't put binaries in the repo, as it causes chaos when merging changes. However a new release will be uploaded today. Don't worry about the installer script, as this acts as a template for us when releasing new versions.
